services:
  - type: web
    name: movies-recommender
    env: python
    plan: free
    pythonVersion: 3.11.9
    buildCommand: |
      pip install --upgrade pip
      pip install setuptools wheel
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
