services:
  - type: web
    name: movies-recommender
    env: docker
    plan: free
    buildCommand: docker build -t movies-recommender .
    startCommand: docker run -p $PORT:8501 movies-recommender
