services:
  - type: web
    name: movies-recommender
    buildCommand: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      rustc --version  # This will check if Rust is installed
      pip install -r requirements.txt
    startCommand: streamlit run app.py


