services:
  - type: web
    name: movies-recommender
    env: python
    plan: free
    pythonVersion: 3.11.9
    buildCommand: bash setup.sh
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
